# Generated by Django 3.2 on 2021-04-15 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_brand', models.CharField(max_length=255, verbose_name='Марка авто')),
                ('model', models.CharField(max_length=255, verbose_name='Модель авто')),
                ('year_of_issue', models.IntegerField(verbose_name='Год выпуска')),
                ('gear_box', models.SmallIntegerField(choices=[(1, 'МКПП'), (2, 'АКПП'), (3, 'Робот')], verbose_name='Тип КПП')),
                ('color', models.CharField(max_length=255, verbose_name='Цвет кузова')),
            ],
            options={
                'verbose_name': 'Машина',
                'verbose_name_plural': 'Машины',
            },
        ),
    ]
